{% set name = "django-bootstrap5" %}
{% set version = "23.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 21e1956a8a819370decc5d365ce4f4207761cb065afec5a7df8c4c8c49507f2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - django >=3.2

test:
  imports:
    - django_bootstrap5
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zostera/django-bootstrap5
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bootstrap 5 for Django
  doc_url: https://github.com/zostera/django-bootstrap5#readme
  dev_url: https://github.com/zostera/django-bootstrap5

extra:
  recipe-maintainers:
    - rxm7706
    - swainn
