{% set name = "django-bootstrap5" %}
{% set version = "24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-bootstrap5-{{ version }}.tar.gz
  sha256: fc272b5bb218690fe6f32d52b23c155ebb46fbc5a2856c84eb353c1bf5fc49ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.8
    - django >=3.2

test:
  imports:
    - django_bootstrap5
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zostera/django-bootstrap5
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bootstrap 5 for Django
  doc_url: https://github.com/zostera/django-bootstrap5#readme
  dev_url: https://github.com/zostera/django-bootstrap5

extra:
  recipe-maintainers:
    - rxm7706
    - swainn
