{% set name = "django-bootstrap5" %}
{% set version = "23.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbf9942a17e1f48b4142e78df9e85afb65e4066a20e38ec7c497d36ae5ef7256

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - django >=3.2
    - beautifulsoup4 >=4.12.2
    - pillow >=9.5.0

test:
  imports:
    - django_bootstrap5
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/zostera/django-bootstrap5
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bootstrap 5 for Django
  doc_url: https://github.com/zostera/django-bootstrap5#readme
  dev_url: https://github.com/zostera/django-bootstrap5

extra:
  recipe-maintainers:
    - swainn
