{% set name = "django-bootstrap5" %}
{% set version = "24.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ca5ec5568fc2a3fc239f0cb8ce41a7df3802b8c4af930d7f64451784ec7ddc16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  imports:
    - django_bootstrap5
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zostera/django-bootstrap5
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bootstrap 5 for Django
  doc_url: https://github.com/zostera/django-bootstrap5#readme
  dev_url: https://github.com/zostera/django-bootstrap5

extra:
  recipe-maintainers:
    - rxm7706
    - swainn
